{{- if and .Values.grafana.enabled .Values.grafana.persistence.enabled ( not .Values.grafana.persistence.preconfiguredPersistentVolumeClaim ) ( not .Values.grafana.persistence.hostPath ) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Release.Name }}-grafana'
  labels:
    app: '{{ .Release.Name }}-grafana'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
  {{- if .Values.grafana.persistence.storageClass }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- else }}
    volume.alpha.kubernetes.io/storage-class: default
  {{- end }}
spec:
  {{- if semverCompare ">= 1.6" ( printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor ) }}
  {{- if .Values.grafana.persistence.storageClass }}
  storageClassName: {{ .Values.grafana.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
  accessModes:
    - {{ .Values.grafana.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.grafana.persistence.size | quote }}
{{- end }}
