{{ if not .Values.kubestatemetrics.useDefaultServiceAccount -}}
apiVersion: rbac.authorization.k8s.io/v1{{- if semverCompare "<= 1.7" ( printf "%s.%s" .Capabilities.KubeVersion.Major .Capabilities.KubeVersion.Minor ) }}beta1{{ end }}
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  labels:
    app: '{{ .Release.Name }}-kube-state-metrics'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-kube-state-metrics-resizer
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-kube-state-metrics
  namespace: {{ .Release.Namespace }}
{{- end }}
