{{ if not .Values.kubestatemetrics.useDefaultServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-kube-state-metrics
  labels:
    app: '{{ .Release.Name }}-kube-state-metrics'
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
{{- end }}
