kind: Secret
metadata:
  name: awsSecret1
spec:
  awsApiAccessKey:
    accessKeyId: <access_key>
    secretAccessKey: <access-secret>
---
kind: Cluster
metadata:
  name: istio4
spec:
  kublrAgentTgzUrl: https://repo.kublr.com/repository/gobinaries/kublr/1.8.0/kublr-1.8.0-linux.tar.gz
  locations:
  - name: aws1
    aws:
      region: us-west-1
      availabilityZones:
      - us-west-1a
      - us-west-1b
      awsApiAccessSecretRef: awsSecret1
  master:
    locations:
    - aws:
        instanceType: t2.large
#        overrideImageId: ami-47c1c427
        availabilityZones:
        - us-west-1a
        sshKey: <ssh_key_name>
      locationRef: aws1
    minNodes: 1
    kublrAgentConfig:
      kublr:
        kube_api_server_flag:
          runtime_config:
            flag: '--runtime-config='
            values:
              admissionregistration:
                value: 'admissionregistration.k8s.io/v1alpha1'
                order: '020'
  nodes:
  - locations:
    - aws:
        instanceType: t2.large
        availabilityZones:
        - us-west-1a
        - us-west-1b
#        overrideImageId: ami-47c1c427
        sshKey: <ssh_key_name>
      locationRef: aws1
    autoscaling: false
    minNodes: 3
  features:
    logging:
      logCollection:
        enabled: true
    monitoring:
      statsCollection:
        enabled: true
    ingress:
      ingressControllers:
      - nginx:
          acme:
            apiUrl:
            email:
            enabled: true
          enabled: true
