imageTag: v0.7.1
cluster:
  name: rook
  monCount: 3
  useAllNodes: true
  useHostNetwork: false
  useAllDevices: false
  deviceFilter:
  metadataDevide:

pool:
  enabled: false
  name: replicapool
  config: {}
#    replicated:
#      size: 2
#    erasureCoded:
#      dataChunks: 2
#      codingChunks: 1

filesystem:
  enabled: false
  name: file-fs
  metadataPool:
    replicated:
      size: 1
  dataPools:
  - replicated:
      size: 1
#  dataChunks: 2
#  codingChunks: 1
  metadataServer:
    activeCount: 1
    activeStandby: true
    nodeAffinity: {}
#      key: kublr.io/node-group
#      value: rook
    resources: {}


storageclass:
  default: true

config: {}
#  pg_num: 512

placement: {}
#  all:
#    key: kublr.io/node-group
#    value: rook
#  api:
#    key: rook/role
#    value: api
#  mgr:
#    key: rook/role
#    value: mgr
#  mon:
#    key: rook/role
#    value: mon
#  osd:
#    key: rook/role
#    value: osd


resources: {}
#  api:
#    limits:
#      cpu: "500m"
#      memory: "1024Mi"
#    requests:
#      cpu: "500m"
#      memory: "1024Mi"
#  mgr: {}
#  mon: {}
#  osd: {}
