apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8020
    name: http
  selector:
    app: helloworld