Dataset: ToTrainDataset.csv # file must exists in ./data folder

Rabbitmq:
  host: localhost
  port: 5672
  username: 'guest'
  password: 'guest'

HPA:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  metricName: rabbitmq_queue_messages_ready_ram
  targetValue: 5000

replicaCount: 1
image:
  repository: kublr/demo-celeryworker
  tag: latest
  pullPolicy: Always

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
