apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-data"
  labels:
    app: "{{ .Release.Name }}-data"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- $files := .Files }}
  {{ .Values.Dataset }}: |
{{ $files.Get (printf "data/%s" .Values.Dataset) | indent 4}}