{{- if .Values.HPA.enabled }}
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: "{{ .Release.Name }}-hpa"
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {{ template "fullname" . }}
  # autoscale between 1 and 10 replicas
  minReplicas: {{ .Values.HPA.minReplicas }}
  maxReplicas: {{ .Values.HPA.maxReplicas }}
  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        targetAverageUtilization: 50
#    - type: Resource
#      resource:
#        name: memory
#        targetAverageValue: 150Mi
    - type: Object
      object:
        metricName: {{ .Values.HPA.metricName  }}
        target:
          apiVersion: v1
          kind: Namespace
          name: default
        targetValue: {{ .Values.HPA.targetValue }}
{{- end }}
