{{- $highAvailability := gt (int .Values.keycloak.replicas) 1 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-keycloak"
  labels:
    app: "{{ .Release.Name }}-keycloak"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "keycloak/*").AsConfig | indent 2 }}
  keycloak.sh: |
    #!/usr/bin/env bash

    set -eu

    /opt/jboss/keycloak/bin/jboss-cli.sh --file=/scripts/keycloak.cli

    args=(-b 0.0.0.0{{ if $highAvailability }} --server-config standalone-ha.xml{{ end }} -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile -Dkeycloak.migration.file=/scripts/iam-realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING)
    #args=(-b 0.0.0.0{{ if $highAvailability }} --server-config standalone-ha.xml{{ end }})
    #args=(-b $EXTERNAL_IP {{ if $highAvailability }} --server-config standalone-ha.xml{{ end }})

    exec /opt/jboss/docker-entrypoint.sh "${args[@]}"
    exit "$?"

  keycloak.cli: |
    embed-server{{ if $highAvailability }} --server-config=standalone-ha.xml{{ end }} --std-out=echo

{{- $cli := .Values.keycloak.cli }}

{{ $cli.nodeIdentifier | indent 4 }}

{{ $cli.logging | indent 4 }}

{{ $cli.reverseProxy | indent 4 }}

{{- if $highAvailability }}
{{ $cli.discovery | indent 4 }}
{{- end }}

{{- if $cli.custom }}
{{ $cli.custom | indent 4 }}
{{- end }}

    stop-embedded-server
