apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-openldap"
  labels:
    app: "{{ .Release.Name }}-openldap"
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.openldap.service.type }}
  ports:
    - port: {{ .Values.openldap.service.externalPort }}
      targetPort: {{ .Values.openldap.service.internalPort }}
      protocol: TCP
      name: {{ .Values.openldap.service.name }}
  selector:
    app: "{{ .Release.Name }}-openldap"
    release: {{ .Release.Name }}