apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: kube-system
  labels:
    app: rabbitmq
spec:
 type: ClusterIP
 ports:
   - name: amqp
     port: 5672
     targetPort: 5672
   - name: api
     port: 15672
     targetPort: 15672
 selector:
   app: rabbitmq
