apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: kube-system
data:
  enabled_plugins: |
    [rabbitmq_management,rabbitmq_shovel].
  rabbitmq.conf: |
    management.load_definitions=/etc/rabbitmq/rabbitmq_definitions.json
    loopback_users = none
  rabbitmq_definitions.json: |
    {
     "rabbit_version": "3.7.3",
     "users": [
       {
         "name": "user",
         "password_hash": "usjBhG87iouIX2bpEc5CRukKoA+rbh7VipNc92i2wSrTpvJO",
         "hashing_algorithm": "rabbit_password_hashing_sha256",
         "tags": ""
       },
       {
         "name": "guest",
         "password_hash": "zvuaq/9PvrbmbyhoO7qKtMqBCjTaGuLcUbY5TpgrEF5AkREa",
         "hashing_algorithm": "rabbit_password_hashing_sha256",
         "tags": "administrator"
       }
     ],
     "vhosts": [
       {
         "name": "/"
       }
     ],
     "permissions": [
       {
         "user": "user",
         "vhost": "/",
         "configure": ".*",
         "write": ".*",
         "read": ".*"
       },
       {
         "user": "guest",
         "vhost": "/",
         "configure": ".*",
         "write": ".*",
         "read": ".*"
       }
     ],
     "topic_permissions": [
       
     ],
     "parameters": [
       
     ],
     "global_parameters": [
       {
         "name": "cluster_name",
         "value": "rabbit@kublr-rabbit1-rabbitmq-bc4576659-lxpwj"
       }
     ],
     "policies": [
       
     ],
     "queues": [
       {
         "name": "from_fluentd_fanout",
         "vhost": "/",
         "durable": true,
         "auto_delete": false,
         "arguments": {
           
         }
       }
     ],
     "exchanges": [
       
     ],
     "bindings": [
       {
         "source": "amq.fanout",
         "vhost": "/",
         "destination": "from_fluentd_fanout",
         "destination_type": "queue",
         "routing_key": "",
         "arguments": {
           
         }
       }
     ]
    }
  advanced.config: |
    [
      {rabbitmq_shovel,
      [ {shovels, [ {to_central_amq,
                      [ {source,
                          [ {protocol, amqp091},
                            {uris, ["amqp://"]},
                            {queue, <<"from_fluentd_fanout">>}
                          ]},
                        {destination,
                          [ {protocol, amqp091},                        
                            {uris, [ "amqp://user:l6sKhSieSZ@aca38a3a011db11e8994d06394cd6012-402521189.eu-central-1.elb.amazonaws.com"]},
                            {publish_fields, [ {exchange, <<"amq.fanout">>}
                                             ]}
                              ]}
                  ]}
                  ]}
      ]}
    ].
  
  
  
  