apiVersion: v1
kind: Service
metadata:
  name: {{ template "zeppelin-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Zeppelin.Component }}"
spec:
  ports:
    - name: http
      port: {{ .Values.Zeppelin.ServicePort }}
      targetPort: {{ .Values.Zeppelin.ContainerPort }}
  selector:
    component: "{{ .Release.Name }}-{{ .Values.Zeppelin.Component }}"
  type: {{ .Values.Zeppelin.ServiceType }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zeppelin-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "{{ .Release.Name }}-{{ .Values.Zeppelin.Component }}"
spec:
  replicas: {{ default 1 .Values.Zeppelin.Replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{ .Release.Name }}-{{ .Values.Zeppelin.Component }}"
  template:
    metadata:
      labels:
        spark: {{ template "zeppelin-fullname" . }}
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        component: "{{ .Release.Name }}-{{ .Values.Zeppelin.Component }}"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: spark
                operator: In
                values:
                - {{ template "worker-fullname" . }}
                - {{ template "master-fullname" . }}
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ template "zeppelin-fullname" . }}
          image: "{{ .Values.Zeppelin.Image }}:{{ .Values.Zeppelin.ImageTag }}"
          ports:
            - containerPort: {{ .Values.Zeppelin.ContainerPort }}
              name: http
          volumeMounts:
            - name: data
              mountPath: /var/lib/spark/data
          resources:
            requests:
              cpu: "{{ .Values.Zeppelin.Cpu }}"
          env:
            - name: SPARK_MASTER
              value: "spark://{{ template "master-fullname" . }}:{{ .Values.Master.ServicePort }}"
      volumes:
      - name: data
        configMap:
          name: "{{ .Release.Name }}-data"
          defaultMode: 0755