apiVersion: v1
kind: Service
metadata:
  name: rook-grafana
  namespace: rook
spec:
  type: LoadBalancer
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: rook-grafana